# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Data

In [2]:
df = pd.read_csv('DailyDelhiClimateTest.csv')
df.head()

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333

# Clean Column

In [5]:
df.dropna(inplace=True)

In [6]:
df.drop(columns=['meantemp', 'wind_speed', 'meanpressure'], axis=1, inplace=True)
df.head()

         date   humidity
0  2017-01-01  85.869565
1  2017-01-02  77.222222
2  2017-01-03  81.888889
3  2017-01-04  70.050000
4  2017-01-05  74.944444

# Custom EWMA

In [7]:
def ewma(beta, series):
    result = [series[0]]
    for n in range(1, len(series)):
        result.append(beta * series[n] + (1 - beta) * result[n - 1])
    return result

In [9]:
ewma_result = ewma(0.9, df['humidity'])

# Pandas EWMA

In [11]:
pd_result = df['humidity'].ewm(alpha=0.9).mean()

In [18]:
display(ewma_result[:5])
display(pd_result[:5])

[np.float64(85.8695652173913),
 np.float64(78.08695652173914),
 np.float64(81.50869565217391),
 np.float64(71.1958695652174),
 np.float64(74.56958695652175)]

0    85.869565
1    78.008344
2    81.504330
3    71.194402
4    74.569474
Name: humidity, dtype: float64

 Both values are same